### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for 'body' in []

### ISSUE THREAD

**Issue by jankeromnes** [JanitorTechnology/selfapi#23]
```
/home/user/janitor/node_modules/selfapi/selfapi.js:324
        if ('body' in exampleResponse) {
                   ^

TypeError: Cannot use 'in' operator to search for 'body' in []
    at ClientRequest.<anonymous> (/home/user/janitor/node_modules/selfapi/selfapi.js:324:20)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at Socket.socketOnData (_http_client.js:454:20)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
npm ERR! Test failed.  See above for more details.
```

**Comment by jankeromnes** [comment]
Not actually a SelfAPI bug, the handler response looked like this:

```js
  examples: [{
    response: '[]'
  }]
```

while it should have been:

```js
  examples: [{
    response: {
      body: '[]'
    }
  }]
```
